/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author ENES
 */
public class OfficerHomePage extends javax.swing.JFrame {

    /**
     * Creates new form OfficerHomePage
     */
    public OfficerHomePage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnChangeUpdate = new javax.swing.JButton();
        btnCreateNewAccount = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();
        btnOfficerSetting = new javax.swing.JButton();
        btnCashOperation = new javax.swing.JButton();
        btnPaymentOperation = new javax.swing.JButton();
        btnCreditApp = new javax.swing.JButton();
        btnCardCreditApp = new javax.swing.JButton();
        btnDeleteAccount = new javax.swing.JButton();
        btnListCustomers = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MBANK - MEMUR ANA İŞLEM EKRANI");

        btnChangeUpdate.setText("Müşteri Bilgileri Değiştir/Güncelle");
        btnChangeUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeUpdateActionPerformed(evt);
            }
        });

        btnCreateNewAccount.setText("Müşteri Hesap Yeni Hesap Açma");
        btnCreateNewAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateNewAccountActionPerformed(evt);
            }
        });

        btnLogOut.setText("OTURUMU KAPAT");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        btnOfficerSetting.setText("MEMUR LOGİN ŞİFRE DEĞİŞTİRME");
        btnOfficerSetting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOfficerSettingActionPerformed(evt);
            }
        });

        btnCashOperation.setText("Müşteri Hesaba Para Yatırma/Çekme");
        btnCashOperation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCashOperationActionPerformed(evt);
            }
        });

        btnPaymentOperation.setText("Tüm Fatura Ödeme İşlemleri(Gişe Ödemeleri)");
        btnPaymentOperation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaymentOperationActionPerformed(evt);
            }
        });

        btnCreditApp.setText("Müşteri Kredi Başvurusu");
        btnCreditApp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreditAppActionPerformed(evt);
            }
        });

        btnCardCreditApp.setText("Müşteri Kredi Kartı Başvurusu");
        btnCardCreditApp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCardCreditAppActionPerformed(evt);
            }
        });

        btnDeleteAccount.setText("Müşteri Hesabı Silme");
        btnDeleteAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteAccountActionPerformed(evt);
            }
        });

        btnListCustomers.setText("Tüm Müşteri Listesi");
        btnListCustomers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListCustomersActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel1.setText("FATURA ÖDEME : BANKA MEMURLARI TARAFINDAN NAKİT OLARAK YAPIILMAKTADIR..");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel2.setText("İSTEYEN MÜŞTERİLERİMİZ KENDİ SİSTEMLERİNDEN HESAP BAKİYELERİ İLE BU İŞLEMLERİ YAPABİLMEKTEDİRLER.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCreateNewAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnDeleteAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCashOperation, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnCardCreditApp, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCreditApp, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnPaymentOperation, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnOfficerSetting, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnChangeUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnListCustomers, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 91, Short.MAX_VALUE))
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreateNewAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnChangeUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnListCustomers, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCashOperation, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCardCreditApp, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreditApp, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPaymentOperation, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOfficerSetting, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        OfficerLogin officerLogin=new OfficerLogin();
        officerLogin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void btnChangeUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeUpdateActionPerformed
      OfficerEditCustomer officerEditCustomer=new OfficerEditCustomer();
      officerEditCustomer.setVisible(true);
      this.dispose();
    }//GEN-LAST:event_btnChangeUpdateActionPerformed

    private void btnListCustomersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListCustomersActionPerformed
        this.setVisible(true);
        OfficerAllCustomerTable officerAllCustomerTable=new OfficerAllCustomerTable();
        officerAllCustomerTable.setVisible(true);
        
    }//GEN-LAST:event_btnListCustomersActionPerformed

    private void btnCreateNewAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateNewAccountActionPerformed
        OfficerAddCustomer officerAddCustomer=new OfficerAddCustomer();
        officerAddCustomer.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCreateNewAccountActionPerformed

    private void btnDeleteAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteAccountActionPerformed
       OfficerDeleteCustomer officerDeleteCustomer=new OfficerDeleteCustomer();
       officerDeleteCustomer.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_btnDeleteAccountActionPerformed

    private void btnCashOperationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCashOperationActionPerformed
        OfficerParaYatır officerParaYatır=new OfficerParaYatır();
        officerParaYatır.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCashOperationActionPerformed

    private void btnCardCreditAppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCardCreditAppActionPerformed
        OfficerCardBasvuru officerCardBasvuru=new OfficerCardBasvuru();
        officerCardBasvuru.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCardCreditAppActionPerformed

    private void btnCreditAppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreditAppActionPerformed
       OfficerCreditBasvuru officerCreditBasvuru=new OfficerCreditBasvuru();
       officerCreditBasvuru.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_btnCreditAppActionPerformed

    private void btnOfficerSettingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOfficerSettingActionPerformed
       OfficerChangePassword officerChangePassword=new OfficerChangePassword();
       officerChangePassword.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_btnOfficerSettingActionPerformed

    private void btnPaymentOperationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaymentOperationActionPerformed
        OfficerAllPaymentOperation officerAllPaymentOperation=new OfficerAllPaymentOperation();
        officerAllPaymentOperation.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPaymentOperationActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OfficerHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OfficerHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OfficerHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OfficerHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OfficerHomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCardCreditApp;
    private javax.swing.JButton btnCashOperation;
    private javax.swing.JButton btnChangeUpdate;
    private javax.swing.JButton btnCreateNewAccount;
    private javax.swing.JButton btnCreditApp;
    private javax.swing.JButton btnDeleteAccount;
    private javax.swing.JButton btnListCustomers;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnOfficerSetting;
    private javax.swing.JButton btnPaymentOperation;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
